[package]
name = "metre-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
Inflector = "0.11.4"
darling = "0.20.3"
proc-macro2 = "1.0.66"
quote = "1.0.32"
regex = "1.10.4"
regex_static = "0.1.1"
syn = "2.0.27"